In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('https://raw.githubusercontent.com/ritaafrica/data/main/network_traffic_data.csv')

In [3]:
df.head()

,Timestamp,Source_IP,Destination_IP,Protocol,Port,Bytes_Sent,Bytes_Received,Status,Threat_Level
0,2025-03-19 13:04:10,10.0.0.15,192.168.1.20,TCP,NaN,5411,8989,Blocked,Low
1,2025-03-19 13:03:40,192.168.1.13,172.217.169.46,ICMP,443.0,4999,11808,Allowed,Medium
2,2025-03-19 13:03:10,10.0.0.5,203.0.113.99,HTTP,443.0,6360,10852,Allowed,Medium
3,2025-03-19 13:02:40,10.0.0.9,192.168.1.20,TCP,NaN,4011,14314,Blocked,Low
4,2025-03-19 13:02:10,192.168.1.4,172.217.169.46,FTP,NaN,5254,8718,Blocked,Medium

In [4]:
df.shape

(1000, 9)

In [5]:
df.columns

Index(['Timestamp', 'Source_IP', 'Destination_IP', 'Protocol', 'Port',
       'Bytes_Sent', 'Bytes_Received', 'Status', 'Threat_Level'],
      dtype='object')

In [6]:
df.info

<bound method DataFrame.info of                Timestamp     Source_IP  Destination_IP Protocol    Port  \
0    2025-03-19 13:04:10     10.0.0.15    192.168.1.20      TCP     NaN
1    2025-03-19 13:03:40  192.168.1.13  172.217.169.46     ICMP   443.0
2    2025-03-19 13:03:10      10.0.0.5    203.0.113.99     HTTP   443.0
3    2025-03-19 13:02:40      10.0.0.9    192.168.1.20      TCP     NaN
4    2025-03-19 13:02:10   192.168.1.4  172.217.169.46      FTP     NaN
..                   ...           ...             ...      ...     ...
995  2025-03-19 04:46:40     10.0.0.46  172.217.169.46      DNS    53.0
996  2025-03-19 04:46:10      10.0.0.3         8.8.8.8     HTTP   443.0
997  2025-03-19 04:45:40      10.0.0.3    192.168.1.20      UDP    21.0
998  2025-03-19 04:45:10  192.168.1.30  172.217.169.46      DNS     NaN
999  2025-03-19 04:44:40  192.168.1.34         8.8.8.8     ICMP  3389.0

     Bytes_Sent  Bytes_Received   Status Threat_Level
0          5411            8989  Blocked          Low
1          4999           11808  Allowed       Medium
2          6360           10852  Allowed       Medium
3          4011           14314  Blocked          Low
4          5254            8718  Blocked       Medium
..          ...             ...      ...          ...
995        2290            6246  Blocked          Low
996        3470           12474  Allowed          Low
997        6655           13170  Blocked          Low
998        7308           13117  Blocked          Low
999         726             279  Allowed          Low

[1000 rows x 9 columns]>

In [7]:
df.describe()

              Port   Bytes_Sent  Bytes_Received
count   874.000000  1000.000000     1000.000000
mean   1819.739130  5143.572000     7562.659000
std    2899.374632  2808.256143     4240.206295
min      21.000000   106.000000      102.000000
25%      22.000000  2857.000000     4025.500000
50%      80.000000  5224.000000     7584.500000
75%    3389.000000  7487.750000    11147.750000
max    8080.000000  9984.000000    14977.000000

In [8]:
df.tail()

,Timestamp,Source_IP,Destination_IP,Protocol,Port,Bytes_Sent,Bytes_Received,Status,Threat_Level
995,2025-03-19 04:46:40,10.0.0.46,172.217.169.46,DNS,53.0,2290,6246,Blocked,Low
996,2025-03-19 04:46:10,10.0.0.3,8.8.8.8,HTTP,443.0,3470,12474,Allowed,Low
997,2025-03-19 04:45:40,10.0.0.3,192.168.1.20,UDP,21.0,6655,13170,Blocked,Low
998,2025-03-19 04:45:10,192.168.1.30,172.217.169.46,DNS,NaN,7308,13117,Blocked,Low
999,2025-03-19 04:44:40,192.168.1.34,8.8.8.8,ICMP,3389.0,726,279,Allowed,Low

In [9]:
threat_level = df[["Source_IP", "Destination_IP", "Threat_Level"]]

In [10]:
threat_level.head()

      Source_IP  Destination_IP Threat_Level
0     10.0.0.15    192.168.1.20          Low
1  192.168.1.13  172.217.169.46       Medium
2      10.0.0.5    203.0.113.99       Medium
3      10.0.0.9    192.168.1.20          Low
4   192.168.1.4  172.217.169.46       Medium

In [23]:
blocked_traffic = df[df["Status"] == "Blocked"]

In [25]:
blocked_traffic.shape

(532, 9)

In [39]:
blocked_traffic = blocked_traffic[["Timestamp", "Source_IP", "Destination_IP", "Threat_Level"]]

In [44]:
blocked_traffic = blocked_traffic[blocked_traffic["Threat_Level"] == "High"]

In [46]:
blocked_traffic.head(10)

               Timestamp     Source_IP  Destination_IP Threat_Level
19   2025-03-19 12:54:40     10.0.0.30    203.0.113.99         High
35   2025-03-19 12:46:40     10.0.0.18    203.0.113.99         High
45   2025-03-19 12:41:40     10.0.0.43  172.217.169.46         High
63   2025-03-19 12:32:40     10.0.0.36         8.8.8.8         High
65   2025-03-19 12:31:40  192.168.1.21  172.217.169.46         High
78   2025-03-19 12:25:10  192.168.1.19        10.0.0.5         High
151  2025-03-19 11:48:40     10.0.0.42    203.0.113.99         High
155  2025-03-19 11:46:40  192.168.1.18  172.217.169.46         High
164  2025-03-19 11:42:10     10.0.0.41        10.0.0.5         High
174  2025-03-19 11:37:10     10.0.0.46        10.0.0.5         High

In [47]:
suspicious_traffic = df[df["Threat_Level"]=="Critical"]

In [49]:
suspicious_traffic.head(10)

,Timestamp,Source_IP,Destination_IP,Protocol,Port,Bytes_Sent,Bytes_Received,Status,Threat_Level
59,2025-03-19 12:34:40,10.0.0.47,192.168.1.20,ICMP,NaN,5885,463,Allowed,Critical
96,2025-03-19 12:16:10,192.168.1.35,203.0.113.99,FTP,8080.0,9371,7189,Allowed,Critical
134,2025-03-19 11:57:10,192.168.1.17,172.217.169.46,DNS,22.0,6714,13124,Blocked,Critical
150,2025-03-19 11:49:10,192.168.1.42,10.0.0.5,HTTP,53.0,2702,634,Allowed,Critical
209,2025-03-19 11:19:40,10.0.0.17,203.0.113.99,TCP,3389.0,5085,10014,Blocked,Critical
212,2025-03-19 11:18:10,192.168.1.23,8.8.8.8,FTP,21.0,7190,10232,Blocked,Critical
219,2025-03-19 11:14:40,10.0.0.30,192.168.1.20,TCP,22.0,2702,4498,Allowed,Critical
232,2025-03-19 11:08:10,10.0.0.3,172.217.169.46,DNS,NaN,2606,11416,Blocked,Critical
251,2025-03-19 10:58:40,192.168.1.48,203.0.113.99,DNS,53.0,7644,5920,Allowed,Critical
256,2025-03-19 10:56:10,10.0.0.31,203.0.113.99,ICMP,22.0,9167,8793,Allowed,Critical

In [52]:
high_data_transfer = df[df["Status"] == "Allowed"]

In [53]:
high_data_transfer = high_data_transfer[high_data_transfer["Bytes_Sent"] > 5000]

In [54]:
high_data_transfer

,Timestamp,Source_IP,Destination_IP,Protocol,Port,Bytes_Sent,Bytes_Received,Status,Threat_Level
2,2025-03-19 13:03:10,10.0.0.5,203.0.113.99,HTTP,443.0,6360,10852,Allowed,Medium
5,2025-03-19 13:01:40,10.0.0.43,172.217.169.46,DNS,53.0,6915,12981,Allowed,Low
7,2025-03-19 13:00:40,192.168.1.36,192.168.1.20,TCP,21.0,5655,119,Allowed,Medium
8,2025-03-19 13:00:10,192.168.1.26,192.168.1.20,FTP,NaN,8170,9498,Allowed,Medium
11,2025-03-19 12:58:40,192.168.1.22,192.168.1.20,UDP,21.0,9412,10161,Allowed,Medium
...,...,...,...,...,...,...,...,...,...
973,2025-03-19 04:57:40,192.168.1.21,203.0.113.99,HTTP,53.0,8239,14039,Allowed,Medium
981,2025-03-19 04:53:40,192.168.1.1,8.8.8.8,ICMP,3389.0,8955,3985,Allowed,Low
984,2025-03-19 04:52:10,192.168.1.40,203.0.113.99,ICMP,21.0,7289,5893,Allowed,Low
988,2025-03-19 04:50:10,192.168.1.48,10.0.0.5,DNS,80.0,8548,13088,Allowed,High
990,2025-03-19 04:49:10,192.168.1.8,10.0.0.5,DNS,22.0,7759,5876,Allowed,Low